apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-mongodb-0
  namespace: wanderlust
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-storage-class
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      pv: mongodb-pv-0
